//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryStoreDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Advertisments = new HashSet<Advertisment>();
            this.CartItems = new HashSet<CartItem>();
            this.OderItems = new HashSet<OderItem>();
        }
    
        public int Id { get; set; }
        public int ProGroupId { get; set; }
        public int Stock { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public Nullable<bool> Display { get; set; }
        public string Description { get; set; }
        public string Information { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertisment> Advertisments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OderItem> OderItems { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
    }
}
